# Generated by Django 2.1.2 on 2018-11-02 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='goodstart', max_length=16)),
                ('label', models.CharField(default='myschedule', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='goodstart', max_length=16)),
                ('label', models.CharField(default='myschedule', max_length=8)),
                ('title', models.CharField(max_length=32)),
                ('text', models.TextField()),
                ('dt_start', models.DateTimeField()),
                ('dt_end', models.DateTimeField()),
            ],
        ),
    ]
