# Generated by Django 2.1.2 on 2018-11-04 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='ts_create',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='ts_updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='dt_end',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='dt_start',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
